#!/bin/bash
OS_name=$(awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release)
case $OS_name in
  '"Ubuntu 16.04.6 LTS"')
    OS_name='ubuntu16'
    sudo apt-get update -y
    sudo apt-get install apache2 -y
    ;;
  '"CentOS Linux 7 (Core)"')
    OS_name='centos7'
    sudo yum update -y
    sudo yum install httpd -y
    ;;
  SunOS)
    OS_name='solaris'
    echo 'OS_name not supported'
    exit 2
    ;;
  *)
    echo 'OS_name not supported'
    exit 2
    ;;
esac



